name: testing
on: [push]
jobs:
  example:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: print env
        run: node --version 
        shell: bash
